title: MA 530 Introduction to Statistical Learning
logo: https://marketbusinessnews.com/wp-content/uploads/2019/03/Statistical-Learning-image-1.jpg
description: text below image
show_download: true
theme: jekyll-theme-slate
